- README.Rmd
- README.md
> add codecov badge to README

- README.Rmd
- README.md
> Install Instructions for mac users

- R/map_fetch.R
I'm pretty sure xyz were being ignored. this should fix it
> pass xyz in map_fetch

- .github/workflows/R-CMD-check.yaml
- .github/workflows/check-standard.yaml
changed sessioninfo::session_info to utils::sessionInfo. Seems to have fixed the github actions problem.
> Fix GitHub actions

- DESCRIPTION
- R/name_backbone_checklist.R
- tests/testthat/test-name_backbone_checklist.R
https://github.com/ropensci/rgbif/issues/505
> fixing name_backbone_checklist bug

- _pkgdown.yml
https://github.com/ropensci/rgbif/issues/537
> updating package docs for pkgdown_check

- README.Rmd
- README.md
https://github.com/ropensci/rgbif/issues/555
> cran check badge update

- vignettes/taxonomic_names.Rmd
https://github.com/ropensci/rgbif/issues/536
> too many choices docs

- R/name_backbone_checklist.R
- man/name_backbone_checklist.Rd
https://github.com/ropensci/rgbif/issues/564
> updating name_backbone_checklist docs verbose arg

- .github/workflows/R-CMD-check.yaml
https://github.com/ropensci/rgbif/issues/566
> workflow v2 rlib actions

- .github/workflows/R-CMD-check.yaml
> trying to fix windows workflow

- DESCRIPTION
dev version bump preparing for CRAN release
> dev version bump

- R/name_backbone_checklist.R
- man/name_backbone_checklist.Rd
- man/occ_data.Rd
- tests/testthat/test-name_backbone_checklist.R
https://github.com/ropensci/rgbif/issues/565
> Adding strict arg to name_backbone_checklist 

- R/name_backbone_checklist.R
- man/name_backbone_checklist.Rd
- tests/testthat/test-name_backbone_checklist.R
https://github.com/ropensci/rgbif/issues/515
> adding support for default values to name_backbone_checklist

- R/name_backbone_checklist.R
- man/name_backbone_checklist.Rd
- tests/testthat/test-name_backbone_checklist.R
https://github.com/ropensci/rgbif/issues/515
> adding is_alternative column to name_backbone_checklist

- vignettes/getting_occurrence_data.Rmd
https://github.com/ropensci/rgbif/issues/575
> adding data quality section

- tests/fixtures/occ_download_meta.yml
- tests/fixtures/occ_download_meta_na_results.yml
- tests/fixtures/occ_download_meta_with_results.yml
- tests/testthat/test-occ_download_meta.R
https://github.com/ropensci/rgbif/issues/593
> fixing real request test for occ_download_meta since the api changed

- R/download_predicate_dsl.R
- man/download_predicate_dsl.Rd
- man/lit_search.Rd
https://github.com/ropensci/rgbif/issues/594
> adding support for occ_download DISTANCE_FROM_CENTROID_IN_METERS

- .github/workflows/R-CMD-check.yaml
- .github/workflows/check-cron.yml
https://github.com/ropensci/rgbif/issues/618
> fix error note on github actions

- R/occ_download.R
- man/dataset_search.Rd
- man/dataset_suggest.Rd
- man/occ_data.Rd
- man/organizations.Rd
https://github.com/ropensci/rgbif/issues/603
> Adding note about how to get full print out of print.occ_download_prep

- .github/workflows/check-cron.yml
- DESCRIPTION
updated to ubuntu 20.04 on real requests
> update to ubuntu 20.04 on real requests

- R/lit_search.R
https://github.com/ropensci/rgbif/issues/610
> fixing lit_search examples for doc site

- R/lit_search.R
- tests/testthat/test-lit_search.R
fixed lit_search but when no results were present
> fixing lit_search bug when no result

- R/download_predicate_dsl.R
https://github.com/ropensci/rgbif/issues/589
> adding undocumented datasetName key

- R/name_suggest.r
- tests/testthat/test-name_suggest.r
https://github.com/ropensci/rgbif/issues/657
> adding warning for limit and tests

- R/occ_count.r
> fixing error message for occ_count facets #686

- R/download_predicate_dsl.R
- R/occ_download.R
- man/download_predicate_dsl.Rd
- man/occ_download.Rd
Adds support for gbifid downloads. 
https://github.com/ropensci/rgbif/issues/711
https://github.com/ropensci/rgbif/issues/665
@olehprylutskyi
> adding support for gbifId downloads

- .github/workflows/R-CMD-check.yaml
https://github.com/ropensci/rgbif/issues/714
> fixing windows build error

- R/download_predicate_dsl.R
- R/geometry_utils.R
- tests/testthat/test-occ_download.R
https://github.com/ropensci/rgbif/issues/720
> adding error message about full downloads

- R/name_lookup.r
- man-roxygen/namelkup.r
- man/name_lookup.Rd
- tests/testthat/test-name_lookup.r
https://github.com/ropensci/rgbif/issues/729
> Name lookup adding constituentKey  

- .github/workflows/rhub.yaml
https://github.com/ropensci/rgbif/issues/733
> adding rhub

- tests/testthat/test-dataset_uuid_funs.R
- tests/testthat/test-occ_count.r
https://github.com/ropensci/rgbif/issues/733
> CRAN check fixes

- .github/workflows/R-CMD-check.yaml
switching to version 3 of GitHub actions upload artifact
> updating to upload actions upload artifact v3

- R/rgbif-package.r
Fix minor typo, intergration -> integration
> Fix typo in docs

- vignettes/gbif_sql_downloads.Rmd
> updating sql downloads docs #770

- vignettes/getting_occurrence_data.Rmd
> add description to article about download formats

- R/map_fetch.R
- vignettes/creating_maps_from_occurrences.Rmd
- vignettes/gbif_sql_downloads.Rmd
- vignettes/getting_occurrence_data.Rmd
updating documentation 
https://github.com/ropensci/rgbif/issues/777
https://github.com/ropensci/rgbif/issues/776
https://github.com/ropensci/rgbif/issues/773
> updating documentation 

- R/occ_download_describe.R
https://github.com/ropensci/rgbif/issues/762
> adding sql documentation to occ_download_describe

- DESCRIPTION
- R/dataset_search.r
- R/organizations.r
- man/dataset_search.Rd
- tests/fixtures/dataset_search.yml
- tests/testthat/test-dataset_search.r
https://github.com/ropensci/rgbif/issues/788
https://github.com/ropensci/rgbif/issues/789
> adding support for installations to dataset_search and organizations
